service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  timeout: 20
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      MONGO_URL: "mongodb+srv://georgekibew:0SEQcsIDnlVkW1ah@cluster1.3ny8hj0.mongodb.net/?retryWrites=true&w=majority"
